### ISSUE TITLE
404 Not Found Error

### ISSUE THREAD

**Issue by slavakurilyak** [JAIJANYANI/Automated-Resume-Screening-System#1]
Running `$ python Main_1.py` on Python 3.6 produces the following error:

<img width="512" alt="screen shot 2018-05-20 at 11 37 14 am" src="https://user-images.githubusercontent.com/6625584/40282301-293365ee-5c22-11e8-828c-1eea769c0b24.png">

**Comment by JAIJANYANI** [comment]
Please check the code-notes before opening an issue, it's http://127.0.0.1:5000/results
