### ISSUE TITLE
Link for Resume Descriptions is not working.

### ISSUE THREAD

**Issue by sagarkarnati** [JAIJANYANI/Automated-Resume-Screening-System#16]
Below link is not working :
https://s3.ap-south-1.amazonaws.com/codebyte-bucket/Resume%26Job_Descriptions.zip

**Comment by PsiPhiTheta** [comment]
Has anyone found an alternative link for this?

**Comment by JAIJANYANI** [comment]
Updated dataset link, check Readme.
