### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by JAIJANYANI** [JAIJANYANI/Automated-Resume-Screening-System#2]
Hello contributors,
Thank you all for swinging by, in the spirit of Hacktoberfest 2018 I'd like to invite you all to contribute to this repo, just update the CONTRIBUTE.md according to the format.

Happy Hacking!

**Format**
- Project Title
- Getting Started
- Prerequisites
- Installing
- Running the tests
- License
- Acknowledgments
- Contributing to the project
- Using the Issue tracker
- Bug Reports
- Feature Request
- Pull Request (New Contributors/Members)
- Maintainers
- Issues

**Comment by marimendes** [comment]
Okay :D

**Comment by marimendes** [comment]
Please check https://github.com/JAIJANYANI/Automated-Resume-Screening-System/pull/4

**Comment by cziem** [comment]
If this issue is still open I'd like to work on it

**Comment by JAIJANYANI** [comment]
> If this issue is still open I'd like to work on it

Yes, It's still open. Go for it
