### ISSUE TITLE
steps for execution

### ISSUE THREAD

**Issue by supreetha23** [JAIJANYANI/Automated-Resume-Screening-System#23]
please tell step by step instructions to execute this project. please reply asap.

**Comment by Shanti424** [comment]
First of all Install all the packages and then  run app.py

**Comment by fgriberi** [comment]
@JAIJANYANI I've added a [PR](https://github.com/JAIJANYANI/Automated-Resume-Screening-System/pull/24) to close this issue and I've also added Docker support.

**Comment by stablexbt** [comment]
Merged the PR, thanks for the support

**Comment by cryptoabhi** [comment]
Merged the PR, thanks for the support
