### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mady143** [JAIJANYANI/Automated-Resume-Screening-System#33]
Hi @eduardosgs @jirawatp @fgriberi @paulo-filho-dev @jofftiquez ,

when i am running python app.py getting an error

**FileNotFoundError
FileNotFoundError: [Errno 2] No such file or directory: './Job_Description/pedescription.txt'**

Thanks and Regards,
Manikantha Sekhar

**Comment by stablexbt** [comment]
Duplicate of #34

**Comment by jofftiquez** [comment]
Hello @mady143 wrong tag. Hehe.
